export default [
  {
    id: 1,
    dataAll: "all",
    description: "Graphic Design",
    data: "graphic",
    url: "./img/graphicDesign/graphic-design1.jpg",
    alt: "Graphic Design",
  },
  {
    id: 2,
    dataAll: "all",
    description: "Graphic Design",
    data: "graphic",
    url: "./img/graphicDesign/graphic-design2.jpg",
    alt: "Graphic Design",
  },
  {
    id: 3,
    dataAll: "all",
    description: "Graphic Design",
    data: "graphic",
    url: "./img/graphicDesign/graphic-design3.jpg",
    alt: "Graphic Design",
  },
  {
    id: 4,
    dataAll: "all",
    description: "Graphic Design",
    data: "graphic",
    url: "./img/graphicDesign/graphic-design4.jpg",
    alt: "Graphic Design",
  },
  {
    id: 5,
    dataAll: "all",
    description: "Graphic Design",
    data: "graphic",
    url: "./img/graphicDesign/graphic-design5.jpg",
    alt: "Graphic Design",
  },
  {
    id: 6,
    dataAll: "all",
    description: "Graphic Design",
    data: "graphic",
    url: "./img/graphicDesign/graphic-design6.jpg",
    alt: "Graphic Design",
  },
  {
    id: 7,
    dataAll: "all",
    description: "Graphic Design",
    data: "graphic",
    url: "./img/graphicDesign/graphic-design7.jpg",
    alt: "Graphic Design",
  },
  {
    id: 8,
    dataAll: "all",
    description: "Graphic Design",
    data: "graphic",
    url: "./img/graphicDesign/graphic-design8.jpg",
    alt: "Graphic Design",
  },
  {
    id: 9,
    dataAll: "all",
    description: "Graphic Design",
    data: "graphic",
    url: "./img/graphicDesign/graphic-design9.jpg",
    alt: "Graphic Design",
  },
  {
    id: 10,
    dataAll: "all",
    description: "Graphic Design",
    data: "graphic",
    url: "./img/graphicDesign/graphic-design10.jpg",
    alt: "Graphic Design",
  },
  {
    id: 11,
    dataAll: "all",
    description: "Graphic Design",
    data: "graphic",
    url: "./img/graphicDesign/graphic-design11.jpg",
    alt: "Graphic Design",
  },
  {
    id: 12,
    dataAll: "all",
    description: "Graphic Design",
    data: "graphic",
    url: "./img/graphicDesign/graphic-design12.jpg",
    alt: "Graphic Design",
  },
  // web-------------------------------------------------
  {
    id: 13,
    dataAll: "all",
    description: "Web Design",
    data: "web",
    url: "./img/webDesign/web-design1.jpg",
    alt: "Web Design",
  },
  {
    id: 14,
    dataAll: "all",
    description: "Web Design",
    data: "web",
    url: "./img/webDesign/web-design2.jpg",
    alt: "Web Design",
  },
  {
    id: 15,
    dataAll: "all",
    description: "Web Design",
    data: "web",
    url: "./img/webDesign/web-design3.jpg",
    alt: "Web Design",
  },
  {
    id: 16,
    dataAll: "all",
    description: "Web Design",
    data: "web",
    url: "./img/webDesign/web-design4.jpg",
    alt: "Web Design",
  },
  {
    id: 17,
    dataAll: "all",
    description: "Web Design",
    data: "web",
    url: "./img/webDesign/web-design5.jpg",
    alt: "Web Design",
  },
  {
    id: 18,
    dataAll: "all",
    description: "Web Design",
    data: "web",
    url: "./img/webDesign/web-design6.jpg",
    alt: "Web Design",
  },
  {
    id: 19,
    dataAll: "all",
    description: "Web Design",
    data: "web",
    url: "./img/webDesign/web-design7.jpg",
    alt: "Web Design",
  },
  {
    id: 20,
    dataAll: "all",
    description: "Web Design",
    data: "web",
    url: "./img/webDesign/web-Design-8.jpeg",
    alt: "Web Design",
  },
  {
    id: 21,
    dataAll: "all",
    description: "Web Design",
    data: "web",
    url: "./img/webDesign/web-Design-9.jpg",
    alt: "Web Design",
  },
  {
    id: 22,
    dataAll: "all",
    description: "Web Design",
    data: "web",
    url: "./img/webDesign/web-Design-10.jpg",
    alt: "Web Design",
  },
  {
    id: 23,
    dataAll: "all",
    description: "Web Design",
    data: "web",
    url: "./img/webDesign/web-Design-11.jpg",
    alt: "Web Design",
  },
  {
    id: 24,
    dataAll: "all",
    description: "Web Design",
    data: "web",
    url: "./img/webDesign/web-Design-12.jpg",
    alt: "Web Design",
  },
  // landing-------------------------------------------------
  {
    id: 25,
    dataAll: "all",
    description: "Landing Pages",
    data: "landing",
    url: "./img/landingPage/landing-page1.jpg",
    alt: "Landing Pages",
  },
  {
    id: 26,
    dataAll: "all",
    description: "Landing Pages",
    data: "landing",
    url: "./img/landingPage/landing-page2.jpg",
    alt: "Landing Pages",
  },
  {
    id: 27,
    dataAll: "all",
    description: "Landing Pages",
    data: "landing",
    url: "./img/landingPage/landing-page3.jpg",
    alt: "Landing Pages",
  },
  {
    id: 28,
    dataAll: "all",
    description: "Landing Pages",
    data: "landing",
    url: "./img/landingPage/landing-page4.jpg",
    alt: "Landing Pages",
  },
  {
    id: 29,
    dataAll: "all",
    description: "Landing Pages",
    data: "landing",
    url: "./img/landingPage/landing-page5.jpg",
    alt: "Landing Pages",
  },
  {
    id: 30,
    dataAll: "all",
    description: "Landing Pages",
    data: "landing",
    url: "./img/landingPage/landing-page6.jpg",
    alt: "Landing Pages",
  },
  {
    id: 31,
    dataAll: "all",
    description: "Landing Pages",
    data: "landing",
    url: "./img/landingPage/landing-page7.jpg",
    alt: "Landing Pages",
  },
  {
    id: 32,
    dataAll: "all",
    description: "Landing Pages",
    data: "landing",
    url: "./img/landingPage/landing-Page-8.webp",
    alt: "Landing Pages",
  },
  {
    id: 33,
    dataAll: "all",
    description: "Landing Pages",
    data: "landing",
    url: "./img/landingPage/landing-Page-9.png",
    alt: "Landing Pages",
  },
  {
    id: 34,
    dataAll: "all",
    description: "Landing Pages",
    data: "landing",
    url: "./img/landingPage/landing-Page-10.jpg",
    alt: "Landing Pages",
  },
  {
    id: 35,
    dataAll: "all",
    description: "Landing Pages",
    data: "landing",
    url: "./img/landingPage/landing-Page-11.webp",
    alt: "Landing Pages",
  },
  {
    id: 36,
    dataAll: "all",
    description: "Landing Pages",
    data: "landing",
    url: "./img/landingPage/landing-Page-12.jpg",
    alt: "Landing Pages",
  },
  // Wordpress-------------------------------------------------
  {
    id: 37,
    dataAll: "all",
    description: "Wordpress",
    data: "wordpress",
    url: "./img/wordpress/wordpress1.jpg",
    alt: "Wordpress",
  },
  {
    id: 38,
    dataAll: "all",
    description: "Wordpress",
    data: "wordpress",
    url: "./img/wordpress/wordpress2.jpg",
    alt: "Wordpress",
  },
  {
    id: 39,
    dataAll: "all",
    description: "Wordpress",
    data: "wordpress",
    url: "./img/wordpress/wordpress3.jpg",
    alt: "Wordpress",
  },
  {
    id: 40,
    dataAll: "all",
    description: "Wordpress",
    data: "wordpress",
    url: "./img/wordpress/wordpress4.jpg",
    alt: "Wordpress",
  },
  {
    id: 41,
    dataAll: "all",
    description: "Wordpress",
    data: "wordpress",
    url: "./img/wordpress/wordpress5.jpg",
    alt: "Wordpress",
  },
  {
    id: 42,
    dataAll: "all",
    description: "Wordpress",
    data: "wordpress",
    url: "./img/wordpress/wordpress6.jpg",
    alt: "Wordpress",
  },
  {
    id: 43,
    dataAll: "all",
    description: "Wordpress",
    data: "wordpress",
    url: "./img/wordpress/wordpress7.jpg",
    alt: "Wordpress",
  },
  {
    id: 44,
    dataAll: "all",
    description: "Wordpress",
    data: "wordpress",
    url: "./img/wordpress/wordpress8.jpg",
    alt: "Wordpress",
  },
  {
    id: 45,
    dataAll: "all",
    description: "Wordpress",
    data: "wordpress",
    url: "./img/wordpress/wordpress9.jpg",
    alt: "Wordpress",
  },
  {
    id: 46,
    dataAll: "all",
    description: "Wordpress",
    data: "wordpress",
    url: "./img/wordpress/wordpress10.jpg",
    alt: "Wordpress",
  },
  {
    id: 47,
    dataAll: "all",
    description: "Wordpress",
    data: "wordpress",
    url: "./img/wordpress/wordpress11.jpg",
    alt: "Wordpress",
  },
  {
    id: 48,
    dataAll: "all",
    description: "Wordpress",
    data: "wordpress",
    url: "./img/wordpress/wordpress12.jpg",
    alt: "Wordpress",
  },
];
